name: example
description: Example

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  collection: ^1.19.1
  any_borders:
    path: ../

flutter:
  uses-material-design: true
  assets:
    - images/