name: any_borders
description: Borders of any shape, fill, align, and shadows

topics:
  - border
  - decoration
  - shadow
  - shape
  - gradient

homepage: https://github.com/andry-brill/a-borders
repository: https://github.com/andry-brill/a-borders
issue_tracker: https://github.com/andry-brill/a-borders/issues

screenshots:
  - description: 'any-borders examples'
    path: example/web/screenshot.png

version: 1.0.0

environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: '>=3.22.0'

dependencies:
  flutter:
    sdk: flutter
  vector_math: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.30.0
  flutter_lints: ^6.0.0

