name: any_borders
description: Universal border box decoration with non-uniform border, custom corners and merged background-border painting
version: 0.0.1
publish_to: none

environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: '>=3.22.0'

dependencies:
  flutter:
    sdk: flutter
